/* AUTO-GENERATED by tools/post_build.ps1 - DO NOT EDIT */
/* Include this before API headers to redirect C calls through dispatch stubs. */

#ifndef __API_DISPATCH_H__
#define __API_DISPATCH_H__

#define Api_Stream_CanRead ApiDispatch_Stream_CanRead
#define Api_Stream_CanWrite ApiDispatch_Stream_CanWrite
#define Api_Stream_Close ApiDispatch_Stream_Close
#define Api_Stream_Construct ApiDispatch_Stream_Construct
#define Api_Stream_IsDone ApiDispatch_Stream_IsDone
#define Api_Stream_Read ApiDispatch_Stream_Read
#define Api_Stream_Write ApiDispatch_Stream_Write

#endif /* __API_DISPATCH_H__ */
