; AUTO-GENERATED by tools/post_build.ps1 — DO NOT EDIT
; Rebuild once after any change to public symbols.

SECTION dispatch

; --- Section: code_compiler ---
EXTERN _main

PUBLIC _PUB_main
_PUB_main: JP _main

; --- Section: sys ---
EXTERN _Stream_CanRead
EXTERN _Stream_CanWrite
EXTERN _Stream_Close
EXTERN _Stream_Construct
EXTERN _Stream_IsDone
EXTERN _Stream_Read
EXTERN _Stream_Write

PUBLIC _PUB_Stream_CanRead
_PUB_Stream_CanRead: JP _Stream_CanRead
PUBLIC _PUB_Stream_CanWrite
_PUB_Stream_CanWrite: JP _Stream_CanWrite
PUBLIC _PUB_Stream_Close
_PUB_Stream_Close: JP _Stream_Close
PUBLIC _PUB_Stream_Construct
_PUB_Stream_Construct: JP _Stream_Construct
PUBLIC _PUB_Stream_IsDone
_PUB_Stream_IsDone: JP _Stream_IsDone
PUBLIC _PUB_Stream_Read
_PUB_Stream_Read: JP _Stream_Read
PUBLIC _PUB_Stream_Write
_PUB_Stream_Write: JP _Stream_Write

